name: Create Daily Standup Discussions (Job)

on:
  schedule:
    - cron:  '0 7 * * 1-5' # Runs M-F at 7:00am UTC

jobs:
  create_discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: adnan-creator/create-standup-discussions@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORGANIZATION_TOKEN }}
        with:
          filename: ".github/STANDUP_TEMPLATE.md"
          organization: "sparkleo-io"
          team_slugs: "development"
